import type { Metadata } from 'next';
import './globals.css';
import ReactQueryProvider from '@/components/providers/ReactQueryProvider';
import RecoilProvider from '@/components/providers/RecoilProvider';
import localFont from 'next/font/local';
import { ReactNode } from 'react';

const font = localFont({
  src: './fonts/PretendardVariable.woff2',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ReactQueryProvider>
          <RecoilProvider>{children}</RecoilProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
