export const BADGE_INFO = {
  first: {
    key: 'first',
    name: '설레는 첫 만남',
    nonAcquiredDes: '',
    acquiredDes: '그루어리에 오신 것을 환영해요',
    nonAcquireImgSrc: '/assets/images/badge/first_white.png',
    acquireImgSrc: '/assets/images/badge/first.png',
  },
  post1: {
    key: 'post1',
    name: '초보 기록가',
    nonAcquiredDes: '첫 번째 기록을 작성해요',
    acquiredDes: '첫 번째 글 작성을 축하해요',
    nonAcquireImgSrc: '/assets/images/badge/post1_white.png',
    acquireImgSrc: '/assets/images/badge/post1.png',
  },
  post10: {
    key: 'post10',
    name: '활발한 기록가',
    nonAcquiredDes: '10일 연속으로 기록을 작성해요',
    acquiredDes: '10일 연속으로 기록을 성공했어요',
    nonAcquireImgSrc: '/assets/images/badge/post10_white.png',
    acquireImgSrc: '/assets/images/badge/post10.png',
  },
  post100: {
    key: 'post100',
    name: '열정의 기록가',
    nonAcquiredDes: '100일 연속으로 기록을 작성해요',
    acquiredDes: '100일 연속으로 기록을 성공했어요',
    nonAcquireImgSrc: '/assets/images/badge/post100_white.png',
    acquireImgSrc: '/assets/images/badge/post100.png',
  },
  earlyBird: {
    key: 'earlyBird',
    name: '얼리버드',
    nonAcquiredDes: '아침 일찍 기록을 작성하다보면 얻을 수 있어요',
    acquiredDes: '부지런한 아침형 기록가시군요!',
    nonAcquireImgSrc: '/assets/images/badge/earlyBird_white.png',
    acquireImgSrc: '/assets/images/badge/earlyBird.png',
  },
  owl: {
    key: 'owl',
    name: '올빼미',
    nonAcquiredDes: '늦은 밤에 기록을 작성하다보면 얻을 수 있어요',
    acquiredDes: '매일 밤 하루를 정리하는 기록가예요',
    nonAcquireImgSrc: '/assets/images/badge/owl_white.png',
    acquireImgSrc: '/assets/images/badge/owl.png',
  },
  balancer: {
    key: 'balancer',
    name: '균형 기록러',
    nonAcquiredDes: '다양한 질문들을 골고루 이용해보세요',
    acquiredDes: '다양한 질문들을 골고루 기록했어요',
    nonAcquireImgSrc: '/assets/images/badge/balancer_white.png',
    acquireImgSrc: '/assets/images/badge/balancer.png',
  },
  godHand: {
    key: 'godHand',
    name: '신의 손',
    nonAcquiredDes: '500자 이상의 긴 글을 작성하다보면 얻을 수 있어요',
    acquiredDes: '긴 글도 문제 없어요 평균 작성한 글자 수 500자 돌파!',
    nonAcquireImgSrc: '/assets/images/badge/godHand_white.png',
    acquireImgSrc: '/assets/images/badge/godHand.png',
  },
  selfWriter: {
    key: 'selfWriter',
    name: '자아 탐험가',
    nonAcquiredDes: '자아탐험의 질문들을 이용해보세요',
    acquiredDes: '자아탐험의 질문들을 10개 이상 이용했어요',
    nonAcquireImgSrc: '/assets/images/badge/selfWriter_white.png',
    acquireImgSrc: '/assets/images/badge/selfWriter.png',
  },
  growthWriter: {
    key: 'growthWriter',
    name: '성장하는 기록가',
    nonAcquiredDes: '회고 템플릿을 자주 이용해보세요',
    acquiredDes: '회고를 30회 이상 작성했어요',
    nonAcquireImgSrc: '/assets/images/badge/growthWriter_white.png',
    acquireImgSrc: '/assets/images/badge/growthWriter.png',
  },
  dailyWriter: {
    key: 'dailyWriter',
    name: '일상 감상가',
    nonAcquiredDes: '하루생각의 질문들을 이용해보세요',
    acquiredDes: '하루생각의 질문들을 30개 이상 이용했어요',
    nonAcquireImgSrc: '/assets/images/badge/dailyWriter_white.png',
    acquireImgSrc: '/assets/images/badge/dailyWriter.png',
  },
  freeWriter: {
    key: 'freeWriter',
    name: '자유로운 기록가',
    nonAcquiredDes: '자유롭게 글을 쓰다보면 얻을 수 있어요',
    acquiredDes: '나만의 글을 30개 이상 기록했어요',
    nonAcquireImgSrc: '/assets/images/badge/freeWriter_white.png',
    acquireImgSrc: '/assets/images/badge/freeWriter.png',
  },
};
